name: Ubuntu Master Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  clone_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wx-common curl git make cmake clang clang-tools libxml2 libxml2-dev nlohmann-json3-dev \
          build-essential libtiff-tools libtiff-opengl libwxgtk-media3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev \
          libwxgtk3.0-gtk3-dev libtiff5 libtiff5-dev libopencl-clang-12-dev python3-clang-14

    - name: Clone PatchIccMAX Repository
      run: |
        git clone https://github.com/xsscx/PatchIccMAX.git
        cd PatchIccMAX
        git checkout master
        cd Build
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wall" \
              -Wno-dev CMake/

    - name: Build Project with Make and Log Output
      run: |
        cd PatchIccMAX/Build
        make > ../../build.log 2>&1 || true  # Log all output to build.log

    - name: Check Build Success
      run: |
        if grep -i "error" build.log; then
          echo "❌ Build Failed. Check build.log for details."
          exit 1
        else
          echo "✅ Build Succeeded."
        fi
