name: "Master Branch Build CI"

on:
  push:
    branches: 
      - "master"
  pull_request:
    branches: 
      - "master"
  workflow_dispatch:

jobs:
  build-macos:
    name: Build and Test macOS Debug (Main Branch CI)
    runs-on: macos-latest
    strategy:
      fail-fast: false

# change to /tmp dir
cd /tmp
/bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/InternationalColorConsortium/DemoIccMAX/refs/heads/master/contrib/Build/cmake/xnu_build_master_branch.zsh)"
cd ../Testing/
# Build ICC Profiles
/bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/InternationalColorConsortium/DemoIccMAX/refs/heads/master/contrib/UnitTest/CreateAllProfiles.sh)"
    # Upload built binaries as artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: main_ci_macos build
        path: DemoIccMAX/Build

    # Check build success
    - name: Check build success
      run: |
        if [ $? -eq 0 ]; then
          echo "✅ Build Succeeded"
        else
          echo "❌ Build Failed"
          exit 1
        fi
