name: "Linux Master Branch | Clang++ Compiler"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-linux:
    name: Build and Test Linux Master Branch with Clang++
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Git anonymous identity
    - name: Set up Git anonymous identity
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          sudo apt-get install -y curl git make cmake clang clang-tools  libxml2 libxml2-dev build-essential  nlohmann-json3-dev

    # Set Clang++ as the default compiler
    - name: Set Clang++ as the compiler
      run: |
        export CC=clang
        export CXX=clang++
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        clang++ --version
        clang --version

    # Clone the DemoIccMAX repository
    - name: Clone the DemoIccMAX repository
      run: |
        git clone https://github.com/InternationalColorConsortium/DemoIccMAX.git
        cd DemoIccMAX
        git checkout master

    # Configure the build with CMake
    - name: Configure the build with CMake
      run: |
        mkdir -p DemoIccMAX/Build
        cd DemoIccMAX/Build
        export CC=clang
        export CXX=clang++
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        clang++ --version
        clang --version
        pwd
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DJSON_MultipleHeaders=ON -Wno-dev Cmake/

    # Build the project using CMake
    - name: Build project with CMake
      run: |
        cd DemoIccMAX/Build
        make -j$(nproc)
        make -j$(nproc)
        make -j$(nproc)

    # Check build success
    - name: Check build success
      run: |
        if [ -f DemoIccMAX/Build/CMakeCache.txt ]; then
          echo "✅ Build configuration exists."
        else
          echo "❌ Build configuration failed."
          exit 1
        fi

    # Upload built binaries as artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: master-build-linux
        path: DemoIccMAX/Build

    # Upload build logs
    - name: Upload build logs
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: DemoIccMAX/Build/CMakeCache.txt
