name: CKBUILD1

on:
  workflow_dispatch:    # Allows manual triggering from the Actions tab in GitHub
  push:                 # Automatically triggers on push events to the PCS_Refactor branch
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git anonymous identity
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Remove existing DemoIccMAX directory (if it exists)
      run: |
        if [ -d "DemoIccMAX" ]; then
          rm -rf DemoIccMAX
        fi

    - name: Checkout Code
      run: |
        git clone https://github.com/InternationalColorConsortium/DemoIccMAX.git
        cd DemoIccMAX/Build
        sudo apt-get install -y wx-common curl git make cmake clang clang-tools libxml2 libxml2-dev nlohmann-json3-dev build-essential libtiff-tools libtiff-dev libtiff5 libtiff-opengl libwxgtk-webview3.0-gtk3

    # Configure the build with CMake (keeping Cmake/ directory)
    - name: Configure the build with CMake
      run: |
         cd DemoIccMAX/Build/
         cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wall" \
              -Wno-dev Cmake/

    # Build the project with make and log output
    - name: Build project with make and log output
      run: |
        cd DemoIccMAX/Build/
        make
        make
        make
        uname -a
        gcc -v
        clang -v
