###############################################################
#
## Copyright (©) 2024 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 19-FEB-2025 1701 EST by David Hoyt (©)
#
## Intent: Poll the Device and Report
#
## TODO: Refactor for all Windows & UNIX Device Reporting
#
#
###############################################################

name: "linux clang scan-build"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-linux:
    name: Build and Test Linux Master Branch with scan-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxml2 libxml2-dev nlohmann-json3-dev build-essential \
            cmake libopencl-clang-17-dev libwxgtk3.2-dev libtiff-dev \
            curl git llvm clang-tools clang-17

      # Ensure scan-build is in PATH
      - name: Ensure scan-build is installed and accessible
        run: |
          export PATH="/usr/lib/llvm-17/bin:$PATH"
          which scan-build || echo "❌ scan-build not found"
          scan-build --version || echo "❌ scan-build version check failed"

      # Clone the DemoIccMAX repository
      - name: Clone the DemoIccMAX repository
        run: |
          git clone https://github.com/InternationalColorConsortium/DemoIccMAX.git
          cd DemoIccMAX
          git checkout master
          echo "Applying patch for gnu_cpp_pr111"
          cat <<EOF > gnu_cpp_pr111.patch
          diff --git a/Tools/CmdLine/IccCommon/IccJsonUtil.cpp b/Tools/CmdLine/IccCommon/IccJsonUtil.cpp
          index 78a78cf..fcf0c6a 100644
          --- a/Tools/CmdLine/IccCommon/IccJsonUtil.cpp
          +++ b/Tools/CmdLine/IccCommon/IccJsonUtil.cpp
          @@ -94,7 +94,6 @@ template <typename T>
           }
           
           // Explicit template instantiations
          -template bool jsonToValue<int>(const json&, int&);
           template std::string arrayToJson<icUInt8Number>(icUInt8Number*, int);
           template std::string arrayToJson<icUInt16Number>(icUInt16Number*, int);
           template std::string arrayToJson<icUInt32Number>(icUInt32Number*, int);
          EOF
          git apply gnu_cpp_pr111.patch

      # Configure the build with scan-build
      - name: Configure the build with scan-build
        run: |
          cd DemoIccMAX/Build
          export CC=clang
          export CXX=clang++
          export PATH="/usr/lib/llvm-17/bin:$PATH"
          scan-build cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Release -Wno-dev Cmake/

      # Run scan-build for static analysis
      - name: Run scan-build for static analysis
        run: |
          cd DemoIccMAX/Build
          export PATH="/usr/lib/llvm-17/bin:$PATH"
          scan-build --status-bugs --keep-going -o scan-build-reports make -j$(nproc) || true
        continue-on-error: true  # Allow the step to complete even if issues are found

      # Upload scan-build reports
      - name: Upload scan-build reports
        uses: actions/upload-artifact@v4
        with:
          name: scan-build-reports
          path: DemoIccMAX/Build/scan-build-reports

      # Evaluate scan-build results and fail if necessary
      - name: Evaluate scan-build results
        run: |
          cd DemoIccMAX/Build/scan-build-reports
          if [ "$(find . -type f -name '*.html' | wc -l)" -gt 0 ]; then
            echo "scan-build completed with warnings. Check the scan-build-reports artifact."
            exit 0  # Continue but log a message
          else
            echo "No scan-build reports generated. Failing the workflow."
            exit 1
          fi

      # Check build success
      - name: Check build success
        run: |
          if [ -f DemoIccMAX/Build/CMakeCache.txt ]; then
            echo "✅ Build configuration exists."
          else
            echo "❌ Build configuration failed."
            exit 1
          fi

      # Upload built binaries as artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: master-build-linux
          path: DemoIccMAX/Build

      # Upload build logs
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: DemoIccMAX/Build/CMakeCache.txt
